config/routes.rb
Rails.application.routes.draw do
  
  resources :admins
  resources :categories
  resources :sellers
  resources :customers
  
  resources :products do
    resources :reviews
  end

  
  devise_for :users, controllers: {registrations: 'registrations'}
  root to: "home#index"

   get "/users", to: "admins#users", as: "users"
  delete "/users/:id", to: "admins#admin_delete_user", as: "admin_delete_user"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/admins/_form.html.erb
<%= simple_form_for(@admin) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
  <%= f.input :first_name, label: "First Name" %>
  <%= f.input :last_name, label: "Last Name" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<h1>Editing Admin</h1>

<%= render 'form', admin: @admin %>

<br>

<% if current_user.admin.id == @admin.id %>
  <%= link_to 'Back', admins_path, class: 'btn btn-secondary' %>
  <%= link_to 'Change My Password', edit_user_registration_path, class: 'btn btn-danger' %>
<% else %>
  <%= link_to 'Back', admins_path, class: 'btn btn-secondary' %>
<% end %>

app/views/admins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admin Page</h1>

<table>
  <thead>
    <tr>
     <th scope="col">First name</th>
      <th scope="col">Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admins.each do |admin| %>
      <tr>
        <td><%= admin.first_name %></td>
        <td><%= admin.last_name %></td>
        <td><%= link_to 'Show', admin %></td>
        <td><%= link_to 'Edit', edit_admin_path(admin) %></td>
        <td><%= link_to 'Destroy', admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin', new_admin_path, class: 'btn btn-outline-primary' %>

app/views/admins/new.html.erb
<h1>New Admin</h1>

<%= render 'form', admin: @admin %>

<%= link_to 'Back', admins_path %>

app/views/admins/show.html.erb
<% if current_user.admin.id == @admin.id %>
  <%= link_to 'Edit My Account', edit_admin_path(@admin) %>
<% else %>
  <%= link_to "Edit Admin's Account", edit_admin_path(@admin) %>
<% end %>

<br>


<p>
  <strong>First name:</strong>
  <%= @admin.first_name.capitalize %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @admin.last_name.capitalize %>
</p>


<%= link_to 'Back', admins_path, class: 'btn btn-secondary' %>

app/views/admins/users.html.erb
<h1>All Users</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Email</th>
      <th scope="col">ID</th>
      <th scope="col">Customer</th>
      <th scope="col">Business/Seller</th>
      <th scope="col">Admin</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.id %></td>
        <td><%= user&.customer? ? user&.customer&.first_name : "-"%></td>
        <td><%= user&.seller? ? user&.seller&.first_name : "-"%></td>
        <td><%= user&.admin? ? user&.admin&.first_name : "-"%></td>
        <td><%= link_to 'Delete', admin_delete_user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>