config/routes.rb
Rails.application.routes.draw do
  
  resources :admins
  resources :categories
  resources :sellers
  resources :customers
  
  resources :products do
    resources :reviews
  end

  
  devise_for :users, controllers: {registrations: 'registrations'}
  root to: "home#index"

   get "/users", to: "admins#users", as: "users"
  delete "/users/:id", to: "admins#admin_delete_user", as: "admin_delete_user"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/seller.rb
class Seller < ApplicationRecord

    belongs_to :user, class_name: 'User', foreign_key: 'user_id'
    has_many :products, dependent: :delete_all

    validates :first_name, presence: true, on: :update
    validates :last_name, presence: true, on: :update

      def phone_number
    if phone != nil || phone != ""
      phone.to_s.delete('^0-9')
      if phone.empty?
        errors.add(:phone, "can't be blank")
      elsif phone.length != 10
        errors.add(:phone, "must be a 10 digit mobile number. eg. '0411222333'")
      elsif phone[0..1] != "04"
        errors.add(:phone, "must be a mobile number starting with '04'")
      end
    end
  end

  
end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController
  before_action :set_seller, only: [:show, :edit, :update, :destroy]

  # GET /sellers
  # GET /sellers.json
  def index
    @sellers = Seller.all
  end

  # GET /sellers/1
  # GET /sellers/1.json
  def show
  end

  # GET /sellers/new
  def new
    @seller = Seller.new
    authorize! :read, @seller, :message => "You do not have authorization to view that content."
  end

  # GET /sellers/1/edit
  def edit
  end

  # POST /sellers
  # POST /sellers.json
  def create
    @seller = Seller.new(seller_params)
    @seller.user = current_user
    authorize! :read, @seller, :message => "You do not have authorization to view that content."

   if @seller.save
    redirect_to edit_seller_path
   else
    render :new
   end
  end

  # PATCH/PUT /sellers/1
  # PATCH/PUT /sellers/1.json
  def update
    respond_to do |format|
      if @seller.update(seller_params)
        format.html { redirect_to @seller, notice: 'Seller was successfully updated.' }
        format.json { render :show, status: :ok, location: @seller }
      else
        format.html { render :edit }
        format.json { render json: @seller.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sellers/1
  # DELETE /sellers/1.json
  def destroy
    @seller.destroy
    respond_to do |format|
      format.html { redirect_to sellers_url, notice: 'Seller was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_seller
      @seller = Seller.find(params[:id])
      authorize! :read, @seller, :message => "You do not have authorization to view that content."
    end

    # Only allow a list of trusted parameters through.
    def seller_params
       params[:seller][:first_name].capitalize!
      params[:seller][:last_name].capitalize!
      params[:seller][:phone] = format_phone_number(params[:seller][:phone])
      params.require(:seller).permit(:first_name, :last_name, :address, :phone)
    end
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/views/sellers/_form.html.erb
<%= form_with(model: seller, local: true) do |form| %>
  <% if seller.errors.any? %>
    <div id="error_explanation">
      <!--<h2><%= pluralize(seller.errors.count, "error") %> prohibited this seller from being saved:</h2>-->

      <ul class="alert alert-warning list-style-none">
        <% seller.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :address %>
    <%= form.search_field :address, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :phone %>
    <%= form.text_field :phone, class: "form-control" %>
  </div>

   <div class="form-group">
    <%= form.label :business_number %>
    <%= form.text_field :business_number, class: "form-control" %>
  </div>


  <div class="actions">
    <%= form.submit 'Update', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/sellers/edit.html.erb
<h1>Editing Seller</h1>

<%= render 'form', seller: @seller %>

<br>

<% if current_user.admin? %>
  <%= link_to 'Back', seller_path, class: 'btn btn-secondary'%>
<% elsif current_user.seller? %>
  <%= link_to 'Back', seller_path(current_user.seller.id), class: 'btn btn-outline-secondary'%>
  <%= link_to 'Change My Password', edit_user_registration_path, class: 'btn btn-outline-danger'%>
<% end %>

app/views/sellers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sellers</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Address</th>
      <th scope="col">Mobile</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sellers.each do |seller| %>
      <tr>

        <td><%= seller.first_name.capitalize + ' ' + seller.last_name.capitalize %></td>
        <td><%= seller.user.email if seller.user.email %></td>
        <td><%= seller.address if seller.address%></td>
        <td><%= "#{seller.phone[0..3]} #{seller.phone[4..6]} #{seller.phone[7..9]}" %></td>
        <td><%= link_to 'Show', seller %></td>
        <td><%= link_to 'Edit', edit_seller_path(seller) %></td>
        <td><%= link_to 'Destroy', seller, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Seller', new_seller_path %>

app/views/sellers/new.html.erb
<h1>New Business</h1>

<%= render 'form', seller: @seller %>

<%= link_to 'Back', sellers_path %>

app/views/sellers/show.html.erb
<!--<p id="notice"><%= notice %></p>-->

<% if current_user.admin? %>
  <%= link_to "Edit Business Account", edit_seller_path(@seller) %>
<% elsif current_user.seller? %>
  <%= link_to 'Edit My Account', edit_seller_path(@seller) %>
  <%= link_to  "Add New Product", new_product_path(@seller) %>
<% end %>

<br>

<p>
  <strong>Name:</strong>
  <%= if @seller&.first_name&.empty? && @seller&.last_name&.empty?
    "N/A"
  else
    @seller&.first_name&.capitalize + ' ' + @seller&.last_name&.capitalize
  end %>
</p>

<p>
  <strong>Email:</strong>
  <%= @seller&.user&.email %>
</p>

<p>
  <strong>Address:</strong>
  <%= @seller&.address&.empty? ? "N/A" : @seller&.address %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @seller&.phone&.empty? ? "N/A" : "#{@seller&.phone[0..3]} #{@seller&.phone[4..6]} #{@seller&.phone[7..9]}" %>
</p>



<%= link_to 'Edit', edit_seller_path(@seller) %> |
<%= link_to 'Back', sellers_path %>