config/routes.rb
Rails.application.routes.draw do
  
  resources :admins
  resources :categories
  resources :sellers
  resources :customers
  
  resources :products do
    resources :reviews
  end

  
  devise_for :users, controllers: {registrations: 'registrations'}
  root to: "home#index"

   get "/users", to: "admins#users", as: "users"
  delete "/users/:id", to: "admins#admin_delete_user", as: "admin_delete_user"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :seller, foreign_key: "seller_id"
    belongs_to :user, foreign_key: "user_id"
    belongs_to :category
    has_many :reviews
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit]

  # GET /products
  # GET /products.json
  def index
        # if params[:category].blank?
        #       @products = Product.all.order("created_at DESC")
        # else
        #       @category_id = Category.find_by(name: params[:category]).id
        #       @products = Product.where(:category_id => @category_id).order("created_at_DESC")
        # end
    @products = Product.all
  end

 
  def show

        if @product.reviews.blank?
                @average_review = 0
        else
          @average_review = @product.reviews.average(:rating).round(2)
        end
  end
 
  def new
    @product = Product.new
    # @product = current_user.products.build
    # @categories = Category.all.map{ |c| [c.name, c.id] }
    @categories = Category.all
    puts "-----------------------------------------"
    puts @categories
  end



   def create
    
    # puts product_params
    # @product = current_user.products.build(product_params)
    # @product = Product.new(product_params)
    # @product = Product.new()
    # @product.name = product_params[:name]
    # @product.description = product_params[:description]
    # @product.price = product_params[:price]

    # category = Category.find_by(id: product_params[:category_id])
    # @product.category = category
    # @product.user = current_user
    # # @product.category_id = params[:category_id]
    # # @product.category = params[:category_id]
    # #@product.user_id = current_user.id
    # puts "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqq"
    # puts @product.inspect
    # puts @product.name
    # puts @product.description
    # puts @product.price
    # puts @product.category
    # puts @product.user

    @product = Product.create(product_params)
    # redirect_to root_path

      if @product.save
        redirect_to products_path
      else
        redirect_to new_product_path
      end
  end

  # def create
  #   # link the current user to the student when they finish filling in all their details
  #   @student = Student.new(student_params)
  #   @student.user = current_user
  #   authorize! :read, @student, :message => "You do not have authorization to view that content."

  #   if @student.save
  #     redirect_to edit_student_path(current_user.student.id), :notice => "Thanks for signup up"
  #   else
  #     render :new, :alert => "Something went wrong, try again"
  #   end

  # end
  
  def edit
  #  @categories = Category.all.map{ |c| [c.name, c.id] }
   @categories = Category.all
  end

  
  def update
    
      @product.category_id = params[:category_id]
      if @product.update(product_params)
       redirect_to product_path(@product)
      else
        render 'edit'
      end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
   redirect_to root_path
  end

  private

        def product_params
          params.require(:product).permit(:name, :description, :price, :category_id, :product_img )
          
        end

        def find_product
          @product = Product.find(params[:id])
          
        end
  
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%
=begin
%>
<%= simple_form_for @product, :html => { :multipart => true } do |f| %>
<%=# f.select(:category_id, options_for_select(categories), :prompt => "Select a category") %> 

<%= f.collection_select :category_id, @categories, :id, :name, prompt: "Select Category" %>

<%= f.input :name, label: "Product name" %>
<%= f.input :description %>
<%= f.input :price %>
<%= f.submit :submit, :class => 'btn btn-default' %>
<% end %>
<%
=end
%>

<div class="container">
  <%= form_with(model: @product, local: true) do |f| %>

  <%#= f.collection_select( :category_id, @categories, :id, :name ) %>
  <%= f.collection_select( :category_id, Category.all, :id, :name ) %>

    <div class="form-group">
      <%= f.label :product_name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>


    <div class="form-group">
      <%= f.label :description %>
      <%= f.search_field :description, class: "form-control"%>
    </div>

    <div class="form-group ">
      <%= f.label :price %>
      <%= f.text_field :price, class: "form-control" %>
    </div>


    <div class="actions">
      <%= f.submit 'Submit', class: 'btn btn-primary btn-lg' %>
    </div>
  <% end %>
</div>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= simple_form_for @product, :html => { :multipart => true } do |f| %>
<%= f.select :category_id, @categories %>
<%= f.input :name %>
<%= f.input :description %>
<%= f.input :price %>
<%= f.button :submit %>
<% end %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<!--<p id="notice"><%= notice %></p>-->
<%
=begin
%>
<h1 class="current-category"><%= params[:category] %></h1>
<%= if @products.count == 0 %>
    <h1>Oops! Sorry! There are no products currently available in this category</h1>
    
<% else %>
    <% @products.each do |product| %>

    <h2><%= link_to product.name, product_path(product)  %><h2>
      <%= link_to Category.find(product.category_id).name, category_path(product.category_id) %>
        <%= link_to 'Show', product %>
        <%= link_to 'Edit', edit_product_path(product) %>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      
    <% end %>

<% end %>
 

<br>

<%= link_to 'Add New Cuisine', new_product_path %>

<%
=end
%>

<h1 class="display-3">All Products</h1>

<div class="container">
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Description</th>
        <th scope="col">Price</th>
        <th scope="col">Category</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% if @products.empty? %>
        <td>You have no products</td>
      <% end %>
      <% @products.each do |product| %>
        <tr>
          <td><%= product&.name %></td>
          <td><%= product&.description %></td>
          <td><%= product&.price %></td>
          <td><%= product&.category&.name %></td>
          <td><%= link_to 'Show', product %></td>
          <td><%= link_to 'Edit', edit_product_path(product) %></td>
          <td><%= link_to 'Delete', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<%= link_to 'Add New Cuisine', new_product_path %>

</div>

app/views/products/new.html.erb
<h1>Create a New Product</h1>

<%#= render 'form', categories: @categories %>



<div class="container">
  <%= form_with(model: @product, local: true) do |f| %>

  <%#= f.collection_select( :category_id, @categories, :id, :name ) %>
  <%= f.collection_select( :category_id, Category.all, :id, :name ) %>

    <div class="form-group">
      <%= f.label :product_name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>


    <div class="form-group">
      <%= f.label :description %>
      <%= f.search_field :description, class: "form-control"%>
    </div>

    <div class="form-group ">
      <%= f.label :price %>
      <%= f.text_field :price, class: "form-control" %>
    </div>


    <div class="actions">
      <%= f.submit 'Submit', class: 'btn btn-primary btn-lg' %>
    </div>
  <% end %>
</div>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<!--<p id="notice"><%= notice %></p>-->
<h2><%= @product.name %></h2>
<h4>Cuisine:<%= @product.category.name %></h4>
<p><%= @product.description %></p>

<%= render @product.reviews %>
<div>
<%= link_to  "Add Review", new_product_review_path(@product) %>
</div>
<%= if user_signed_in? %>
    <%= if @product.user_id == current_user.id %>
        <%= link_to 'Edit', edit_product_path(@product) %> 
        <%= link_to  "Delete", product_path(@product), method: :delete, data: {confirm: "Are you sure?"} %>
        <%= link_to 'Back', products_path %>
    <% end %>
<% end %>