config/routes.rb
Rails.application.routes.draw do
  
  resources :admins
  resources :categories
  resources :sellers
  resources :customers
  
  resources :products do
    resources :reviews
  end

  
  devise_for :users, controllers: {registrations: 'registrations'}
  root to: "home#index"

   get "/users", to: "admins#users", as: "users"
  delete "/users/:id", to: "admins#admin_delete_user", as: "admin_delete_user"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_product
  before_action :find_review, only: [:edit, :update, :destory]

 
  def index
    @reviews = Review.all
  end

  
  def show
  end

  def new
    @review = Review.new
  end

  
  def edit
    
  end


  def create
    @review = Review.new(review_params)
    @review.product_id = product.id
    @review.customer_id = current_customer.id
      if @review.save
       redirect_to product_path(@product)
      else
        render "new"
      end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
      if @review.update(review_params)
        redirect_to product_path(@product)
      else
        render 'edit'
      end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    redirect_to product_path(@product)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # def set_review
    #   @review = Review.find(params[:id])
    # end

    # Only allow a list of trusted parameters through.
    def review_params
      params.require(:review).permit(:rating, :comment)
    end

    def find_product
      @product = Product.find(params[:product_id])
      
    end

    def find_review
      @review = Review.find(params[:id])
      
    end
    
    
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= <%= simple_form_for([@product, @product.reviews.build]) do |f| %>

<%= f.input :rating %>
<%= f.input :comment %>
<%= f.button :submit %>

<% end %>


<!--<%= form_with(model: review, local: true) do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
        <% review.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>-->

app/views/reviews/_reviews.html.erb
<p><%= review.rating %></p>
<p><%= review.comment %></p>

<%= link_to  "Edit", edit_product_review_path(review.product, review) %>
<%= link_to  "Delete", product_review_path(review.product, review), method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= simple_form_for([@product, @review]) do |f| %>

<%= f.input :rating %>
<%= f.input :comment %>
<%= f.button :submit %>
<% end %>



<%= render 'form', review: @review %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>